import { Task, DailyObjective } from '../types';

export function createSchoolDayTemplateTasks(date: string): Omit<Task, 'id' | 'createdAt' | 'updatedAt'>[] {
  return [
    {
      date,
      title: 'Wake Up & Hydrate',
      description: 'Zero snooze. Direct awakening, cold water.',
      category: 'RECOVERY',
      startTime: '05:30',
      endTime: '05:45',
      priority: 'CRITICAL',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 15,
      completed: false,
      recurring: 'WEEKDAYS',
      tags: ['routine', 'discipline'],
    },
    {
      date,
      title: 'Morning Preparation & Logistics',
      description: 'Pack books, uniform check, breakfast, review daily tactical objectives.',
      category: 'PERSONAL',
      startTime: '05:45',
      endTime: '06:00',
      priority: 'HIGH',
      difficulty: 'EASY',
      estimatedDurationMinutes: 15,
      completed: false,
      recurring: 'WEEKDAYS',
      tags: ['morning', 'prep'],
    },
    {
      date,
      title: 'School // Core Academic Operations',
      description: 'Focus during lectures. Complete assignments in free periods. Total mental engagement.',
      category: 'ACADEMICS',
      startTime: '06:00',
      endTime: '15:00',
      priority: 'CRITICAL',
      difficulty: 'HARD',
      estimatedDurationMinutes: 540,
      completed: false,
      recurring: 'WEEKDAYS',
      tags: ['school', 'lectures'],
    },
    {
      date,
      title: 'Transit & Mental Reset',
      description: 'Commute home, disconnect from school noise, reset cognitive focus.',
      category: 'RECOVERY',
      startTime: '15:00',
      endTime: '15:30',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'WEEKDAYS',
      tags: ['transit', 'reset'],
    },
    {
      date,
      title: 'Nutritional Refuel & Rest',
      description: 'Clean nutrition, hydration, light rest before deep work.',
      category: 'RECOVERY',
      startTime: '15:30',
      endTime: '16:00',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'WEEKDAYS',
      tags: ['nutrition'],
    },
    {
      date,
      title: 'Academic Deep Work Block',
      description: 'Zero distractions. High cognitive load problem solving, hardest subject first.',
      category: 'ACADEMICS',
      startTime: '16:00',
      endTime: '18:00',
      priority: 'CRITICAL',
      difficulty: 'HARD',
      estimatedDurationMinutes: 120,
      completed: false,
      recurring: 'DAILY',
      tags: ['deep-work', 'core-study'],
    },
    {
      date,
      title: 'Physical Training Session',
      description: 'Strength training, calisthenics or high intensity conditioning.',
      category: 'FITNESS',
      startTime: '18:00',
      endTime: '19:00',
      priority: 'HIGH',
      difficulty: 'HARD',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'DAILY',
      tags: ['workout', 'training'],
    },
    {
      date,
      title: 'Dinner & Physical Recovery',
      description: 'Post-workout protein meal, stretch, shower.',
      category: 'RECOVERY',
      startTime: '19:00',
      endTime: '20:00',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'DAILY',
      tags: ['recovery', 'dinner'],
    },
    {
      date,
      title: 'Academic Revision & Notes Consolidation',
      description: 'Spaced repetition, formulas, flashcards, problem sets.',
      category: 'ACADEMICS',
      startTime: '20:00',
      endTime: '21:30',
      priority: 'HIGH',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 90,
      completed: false,
      recurring: 'DAILY',
      tags: ['revision', 'retention'],
    },
    {
      date,
      title: 'Strategic Review & After-Action Report',
      description: 'Analyze today’s execution metrics. Identify bottlenecks. Lock tomorrow’s plan.',
      category: 'PERSONAL',
      startTime: '21:30',
      endTime: '22:00',
      priority: 'HIGH',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'DAILY',
      tags: ['strategy', 'aar'],
    },
    {
      date,
      title: 'Night Protocol & Sleep Preparation',
      description: 'Screens off, reading or journaling, dark cold room setup.',
      category: 'RECOVERY',
      startTime: '22:00',
      endTime: '22:30',
      priority: 'HIGH',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'DAILY',
      tags: ['sleep-prep'],
    },
  ];
}

export function createHolidayTemplateTasks(date: string): Omit<Task, 'id' | 'createdAt' | 'updatedAt'>[] {
  return [
    {
      date,
      title: 'Wake Up & Morning Protocol',
      description: 'Clean wake at 05:30. Hydration, breathing, mindset alignment.',
      category: 'RECOVERY',
      startTime: '05:30',
      endTime: '06:00',
      priority: 'CRITICAL',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'DAILY',
      tags: ['discipline', 'wake'],
    },
    {
      date,
      title: 'Morning Physical Training',
      description: 'Cardio, calisthenics or martial arts conditioning.',
      category: 'FITNESS',
      startTime: '06:00',
      endTime: '07:00',
      priority: 'HIGH',
      difficulty: 'HARD',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['fitness', 'workout'],
    },
    {
      date,
      title: 'Post-Workout Recovery & Fuel',
      description: 'High protein breakfast, shower, mental prep.',
      category: 'RECOVERY',
      startTime: '07:00',
      endTime: '07:30',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['fuel', 'recovery'],
    },
    {
      date,
      title: 'Deep Academic Work Block I',
      description: 'Primary hard academic concept. 2.5 hours uninterrupted focus.',
      category: 'ACADEMICS',
      startTime: '07:30',
      endTime: '10:00',
      priority: 'CRITICAL',
      difficulty: 'EXTREME',
      estimatedDurationMinutes: 150,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['deep-work', 'syllabus'],
    },
    {
      date,
      title: 'Deliberate Rest / Walk',
      description: 'Cerebral break. No phone, eye relaxation.',
      category: 'RECOVERY',
      startTime: '10:00',
      endTime: '10:30',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['break'],
    },
    {
      date,
      title: 'Coding / Technical Skill Mastery',
      description: 'Algorithms, systems development, project code.',
      category: 'CODING',
      startTime: '10:30',
      endTime: '12:30',
      priority: 'HIGH',
      difficulty: 'HARD',
      estimatedDurationMinutes: 120,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['coding', 'engineering'],
    },
    {
      date,
      title: 'Lunch & Reset',
      description: 'Balanced nutrition and hydration.',
      category: 'RECOVERY',
      startTime: '12:30',
      endTime: '13:30',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['lunch'],
    },
    {
      date,
      title: 'Targeted Academic Revision',
      description: 'Formula drills, test questions, error analysis.',
      category: 'ACADEMICS',
      startTime: '13:30',
      endTime: '15:00',
      priority: 'HIGH',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 90,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['revision', 'tests'],
    },
    {
      date,
      title: 'Cognitive Reset & Rest',
      description: 'Power rest / physical relaxation.',
      category: 'RECOVERY',
      startTime: '15:00',
      endTime: '16:00',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['rest'],
    },
    {
      date,
      title: 'Project / Creative Skill Execution',
      description: 'Applied technical projects, writing, or strategic research.',
      category: 'PROJECT',
      startTime: '16:00',
      endTime: '18:00',
      priority: 'HIGH',
      difficulty: 'HARD',
      estimatedDurationMinutes: 120,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['project', 'applied'],
    },
    {
      date,
      title: 'Mobility & Tactical Walk',
      description: 'Aerobic recovery and mobility work.',
      category: 'FITNESS',
      startTime: '18:00',
      endTime: '19:00',
      priority: 'NORMAL',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['mobility', 'walk'],
    },
    {
      date,
      title: 'Dinner & Downtime',
      description: 'Nutrition, unwind, family / quiet time.',
      category: 'RECOVERY',
      startTime: '19:00',
      endTime: '20:00',
      priority: 'NORMAL',
      difficulty: 'EASY',
      estimatedDurationMinutes: 60,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['dinner'],
    },
    {
      date,
      title: 'Reading / Strategic Literature',
      description: 'Deep non-fiction reading, philosophy, analytical strategy.',
      category: 'READING',
      startTime: '20:00',
      endTime: '21:30',
      priority: 'HIGH',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 90,
      completed: false,
      recurring: 'WEEKENDS',
      tags: ['reading', 'mindset'],
    },
    {
      date,
      title: 'Daily Review // After-Action Report',
      description: 'Execute honest data review. Rate discipline and focus.',
      category: 'PERSONAL',
      startTime: '21:30',
      endTime: '22:00',
      priority: 'HIGH',
      difficulty: 'MEDIUM',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'DAILY',
      tags: ['review'],
    },
    {
      date,
      title: 'Tomorrow Planning & Sleep Prep',
      description: 'Prepare tomorrow’s timetable. Cool room, shut down all devices.',
      category: 'RECOVERY',
      startTime: '22:00',
      endTime: '22:30',
      priority: 'HIGH',
      difficulty: 'EASY',
      estimatedDurationMinutes: 30,
      completed: false,
      recurring: 'DAILY',
      tags: ['sleep'],
    },
  ];
}

export function createDefaultObjectives(date: string): Omit<DailyObjective, 'id' | 'createdAt' | 'updatedAt'>[] {
  return [
    {
      date,
      type: 'PRIMARY',
      text: 'Execute planned academic deep work without deviation',
      completed: false,
    },
    {
      date,
      type: 'SECONDARY',
      text: '2 hours coding or project technical practice',
      completed: false,
    },
    {
      date,
      type: 'SECONDARY',
      text: 'Complete 60 minutes physical training session',
      completed: false,
    },
    {
      date,
      type: 'SECONDARY',
      text: 'Finish daily problem set revision',
      completed: false,
    },
    {
      date,
      type: 'NON_NEGOTIABLE',
      text: 'Wake up on schedule (05:30) with zero snooze',
      completed: false,
    },
    {
      date,
      type: 'NON_NEGOTIABLE',
      text: 'Complete scheduled academic blocks in full',
      completed: false,
    },
    {
      date,
      type: 'NON_NEGOTIABLE',
      text: 'Perform night After-Action Review honestly',
      completed: false,
    },
    {
      date,
      type: 'NON_NEGOTIABLE',
      text: 'Zero unauthorized social media or distraction loops',
      completed: false,
    },
  ];
}
